quarkus.datasource.db-kind=postgresql

# Let Render env vars supply URL/credentials
quarkus.hibernate-orm.database.generation=none

# REQUIRED for poolers
quarkus.hibernate-orm.jdbc.statement-batch-size=0
